modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/davidjjung/drizzleproof/issues"
license = "MIT License"

[[mods]]
modId = "drizzleproof"
version = "${file.jarVersion}"
logoFile = "logo.png"
itemIcon = "minecraft:scaffolding"
configBackground = "minecraft:textures/block/scaffolding_top.png"
authors = "DavigJ"
credits = "Idea credit to Zym, and Jasmine for code suggestions"
displayURL = "https://github.com/davidjjung/drizzleproof"
displayName = "Drizzleproof"
description = '''
    Breaking certain blocks causes their item entities to drop straight downwards, without scattering.
    '''

[[dependencies.drizzleproof]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drizzleproof]]
modId = "forge"
mandatory = true
versionRange = "[43.3.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.drizzleproof]]
modId = "blueprint"
mandatory = true
versionRange = "[6.2.0,)"
ordering = "AFTER"
side = "BOTH"