modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/davidjjung/drizzleproof/issues"
license = "MIT License"

[[mixins]]
config = "drizzleproof.mixins.json"

[[mods]]
modId = "drizzleproof"
version = "${mod_version}"
logoFile = "logo.png"
itemIcon = "minecraft:scaffolding"
configBackground = "minecraft:textures/block/scaffolding_top.png"
authors = "DavigJ"
credits = "Zym, Jasmine"
displayURL = "https://modrinth.com/project/drizzleproof"
displayName = "Drizzleproof"
description = '''
    Breaking certain blocks causes their item entities to drop straight downwards, without scattering.
    '''

[[dependencies.drizzleproof]]
modId = "minecraft"
type = "required"
versionRange = "[${mc_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.drizzleproof]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "AFTER"
side = "BOTH"